In [3]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as cp
import numpy.linalg 

In [4]:
q1=np.random.normal(0,5,20)
q2=np.random.normal(20,10,30)
q3=np.random.normal(50,5,10)
m1=20; m2=30; m3=10; M=60; d=1;

In [5]:
E11=np.kron(np.eye(m1),np.ones([1,M]))
E12=np.kron(np.eye(m2),np.ones([1,M]))
E13=np.kron(np.eye(m3),np.ones([1,M]))

In [6]:
E1=cp.block_diag(E11,E12,E13)

In [7]:
E1_=np.concatenate((E1,np.zeros([M,M])),axis=1)

In [8]:
E1_.shape

(60, 3660)

In [9]:
E21=np.kron(np.ones([1,m1]),np.eye(M));
E22=np.kron(np.ones([1,m2]),np.eye(M));
E23=np.kron(np.ones([1,m3]),np.eye(M));
E2=cp.block_diag(E21,E22,E23)

In [10]:
N=3

In [11]:
E3=np.kron(-np.ones([N,1]),np.eye(M))
E3.shape

(180, 60)

In [12]:
E2_=np.concatenate((E2,E3),axis=1)

In [13]:
E2_.shape

(180, 3660)

In [14]:
E4_=np.concatenate([np.zeros([1,M*M]),np.ones([1,M])],axis=1)

In [15]:
E4_.shape

(1, 3660)

In [16]:
A=np.concatenate([E1_,E2_,E4_],axis=0)

In [17]:
A.shape

(241, 3660)

In [18]:
index=[i*M for i in range(1,N+1)]

In [19]:
index

[60, 120, 180]

In [20]:
A=np.delete(A,index,axis=0)

In [21]:
A.shape

(238, 3660)

In [22]:
numpy.linalg.matrix_rank(A)

238

In [23]:
b=np.concatenate([np.ones([1,m1])/m1,np.ones([1,m2])/m2,np.ones([1,m3])/m3,np.zeros([1,M*N]),np.ones([1,1])],axis=1)

In [24]:
b=np.transpose(b)

In [25]:
b.shape

(241, 1)

In [26]:
b=np.delete(b,index,axis=0)

In [27]:
b.shape

(238, 1)

In [29]:
q=np.concatenate([q1,q2,q3])

In [30]:
d1=[]
for i in range(m1):
    for j in range(M):
        d1.append((q1[i]-q[j])**2)
d1=np.array(d1)

In [31]:
d2=[]
for i in range(m2):
    for j in range(M):
        d2.append((q2[i]-q[j])**2)
d2=np.array(d2)

In [32]:
d3=[]
for i in range(m3):
    for j in range(M):
        d3.append((q3[i]-q[j])**2)
d3=np.array(d3)

In [33]:
c=np.concatenate([d1,d2,d3,np.zeros([M])])

In [34]:
c.shape

(3660,)

In [35]:
c=np.reshape(c,[-1,1])
c.shape

(3660, 1)

In [36]:
np.save("P2A",A)

In [37]:
np.save("P2b",b)

In [38]:
np.save("P2c",c)

In [39]:
q1

array([ 2.13647389, -2.64470809,  5.84631894, -6.98020947, -2.94254153,
        0.04958081, -6.58950368,  0.95205625, -5.73286034, -0.09772471,
       -1.41441751,  4.08656681, -3.81226385,  0.27255582, -5.02069786,
       -3.17954019,  7.19494216, -8.38522149, -9.47602305,  4.71295821])

In [40]:
q2

array([23.77506235, 25.90793152, 14.44796339, 13.38625086, 30.95782642,
       27.63501945, 21.09838795, 20.29635571, 22.97877629,  7.55646666,
       10.80359335, 26.43684217, 21.24387921, 36.68363111,  8.70643644,
       37.63070613,  6.77734705, 17.01520291, 10.23293397, 13.87057592,
       28.4110526 ,  3.84849208, 36.09820298, 31.27980933, 34.43577525,
       21.61291983,  8.28579134, 17.27605099, 13.98069211, 18.94498462])

In [41]:
q3

array([51.01611139, 61.37384657, 54.58824101, 54.24744202, 57.46986682,
       51.05774993, 44.22655963, 47.22199274, 47.96861929, 48.65183471])

In [42]:
np.save("P2q",[q1,q2,q3])

/Users/bob_j_zou/venv/lib/python3.9/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


In [43]:
b

array([[0.05      ],
       [0.05      ],
       [0.05      ],
       [0.05      ],
       [0.05      ],
       [0.05      ],
       [0.05      ],
       [0.05      ],
       [0.05      ],
       [0.05      ],
       [0.05      ],
       [0.05      ],
       [0.05      ],
       [0.05      ],
       [0.05      ],
       [0.05      ],
       [0.05      ],
       [0.05      ],
       [0.05      ],
       [0.05      ],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.03333333],
       [0.033